### PR TITLE
Feat/get time slots

### PR DESCRIPTION
**Pull request by karlknowit**
# What was solved
Creating a service which returned meeting time slots within a bigger time span. This is done so that users can select a booking time slot in the application

# How was it solved
Solved it by fetching the time spans a specific administrator has and calculate how many time slots that fits into that time span. 

# Why was it solved in this way
The agreed way of solving this is to use the newly created endpoints which returns available time spans for a specific user and let our lambda function calculate how many time slots that fits into that span. If the time slot fits depends on how long the meeting is and how big the meeting buffer is, which is send to the lambda function as parameters.

# How was it tested
Solved it by creating a "MH bokningsbar tid" event in my outlook calendar (in outlook test environment) which made the time span searchable. Send as parameters to the newly created lambda function attendees, startTime, endTime, meetingDuration and meetingBuffer and checked the returned result.

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/257)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-1hdqgrb Backend som tar fram tillgängliga tider (timeslots) för specifik handläggare](https://app.clickup.com/t/1hdqgrb)

**Review by sepehrnoor — CHANGES_REQUESTED** [review]
Looks good, just a small nitpick.

**Comment by sepehrnoor** [comment]
Also, tests are failing, the times are offset by -1 hours in the received responses (i.e. we get 8:00:00, when we expect 9:00:00). Looks like a time zone problem.

**Comment by sepehrnoor** [comment]
All the tests pass on my local machine. git's local time-zone is causing the problem.

**Comment by karlknowit** [comment]
Closed in favour for:
https://github.com/helsingborg-stad/helsingborg-io-sls-api/pull/261

**Pull request closed without merging**
