### PR TITLE
build(yarn): the xml2js package in navet-ms was causing issues

### PR DESCRIPTION
**Pull request by TeddyAndersson**
The service navet-ms had a seperate package.json from the intial monorepo setup, this setup was
causing deploy issues due to conflicts in webpack for serverless. This could be solved by moving the
package xml2js into the root package.json

```bash
Serverless: Fetch dependency graph from /Users/jacob/Work/helsingborg-io-sls-api/services/navet-ms/package.json
  Error --------------------------------------------------
  Error: yarn list --depth=1 --json --production failed with code 1
      at ChildProcess.<anonymous> (/Users/jacob/Work/helsingborg-io-sls-api/node_modules/serverless-webpack/lib/utils.js:91:16)
      at ChildProcess.emit (events.js:314:20)
      at ChildProcess.EventEmitter.emit (domain.js:486:12)
      at maybeClose (internal/child_process.js:1047:16)
      at Socket.<anonymous> (internal/child_process.js:438:11)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:486:12)
      at Pipe.<anonymous> (net.js:672:12)
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 ```

### CODE REVIEW

**Review by jwinding — APPROVED** [review]
Well, this is what solved my issue, so yeah...

**Review by dannil76 — CHANGES_REQUESTED** [review]
Disagree to put this in root.
The package is specific to this service. Nothing that other services use. What's wrong with deploy?

**Comment by TeddyAndersson** [comment]
> Disagree to put this in root.
> The package is specific to this service. Nothing that other services use. What's wrong with deploy?
> Again this was approved in earlier PR?!
Sorry for not being mor specific about the reason of this fix. I understand that it might cause confusion.

I do not know why this issue has occured, but for some reason the serverless deploy command gets stuck in the webpack build process. My conclusion to this is that the package.json in the navet-ms and some other services causes a conflict in the build process with the root package.json. I do not know why this conflict occurs but the problem does solve itself when you move a dependency from a service package.json to the root package.json. 

If you @dannil76 have any other thoughts on the matter it would be great (y)

**Comment by TeddyAndersson** [comment]
> The service navet-ms had a seperate package.json from the intial monorepo setup, this setup was
> causing deploy issues due to conflicts in webpack for serverless. This could be solved by moving the
> package xml2js into the root package.json
> 
> ```shell
> Serverless: Fetch dependency graph from /Users/jacob/Work/helsingborg-io-sls-api/services/navet-ms/package.json
>   Error --------------------------------------------------
>   Error: yarn list --depth=1 --json --production failed with code 1
>       at ChildProcess.<anonymous> (/Users/jacob/Work/helsingborg-io-sls-api/node_modules/serverless-webpack/lib/utils.js:91:16)
>       at ChildProcess.emit (events.js:314:20)
>       at ChildProcess.EventEmitter.emit (domain.js:486:12)
>       at maybeClose (internal/child_process.js:1047:16)
>       at Socket.<anonymous> (internal/child_process.js:438:11)
>       at Socket.emit (events.js:314:20)
>       at Socket.EventEmitter.emit (domain.js:486:12)
>       at Pipe.<anonymous> (net.js:672:12)
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> ```

Updated the PR description with the error that @jwinding got when trying to deploy navet-ms

**Comment by dannil76** [comment]
Make sure you have the latest serverless installed as a global package
ie.
$npm i serverless -g

Please try again and let me know if it works.

**Comment by TeddyAndersson** [comment]
> > The service navet-ms had a seperate package.json from the intial monorepo setup, this setup was
> > causing deploy issues due to conflicts in webpack for serverless. This could be solved by moving the
> > package xml2js into the root package.json
> > ```shell
> > Serverless: Fetch dependency graph from /Users/jacob/Work/helsingborg-io-sls-api/services/navet-ms/package.json
> >   Error --------------------------------------------------
> >   Error: yarn list --depth=1 --json --production failed with code 1
> >       at ChildProcess.<anonymous> (/Users/jacob/Work/helsingborg-io-sls-api/node_modules/serverless-webpack/lib/utils.js:91:16)
> >       at ChildProcess.emit (events.js:314:20)
> >       at ChildProcess.EventEmitter.emit (domain.js:486:12)
> >       at maybeClose (internal/child_process.js:1047:16)
> >       at Socket.<anonymous> (internal/child_process.js:438:11)
> >       at Socket.emit (events.js:314:20)
> >       at Socket.EventEmitter.emit (domain.js:486:12)
> >       at Pipe.<anonymous> (net.js:672:12)
> >      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
> > ```
> 
> Updated the PR description with the error that @jwinding got when trying to deploy navet-ms

My thoughts on this is that during the deploy the service package.json does not include all the dependencies that are required for some of the utility functions that are imported into the service, which causes the  build to fail. But i do not know why the  

> Make sure you have the latest serverless installed as a global package
> ie.
> $npm i serverless -g
> 
> Please try again and let me know if it works.

@jwinding

**Comment by jwinding** [comment]
@TeddyAndersson @dannil76 , I removed the node_modules folders from both the root and navet-ms, and then upgraded all my global packages, because indeed my serverless version was way behind the latest. Then I ran yarn in both the root and navet-ms again, and then after deploying it, it now works, so it seems to be a problem with outdated global serverless version? Quite strange, I think... But since it now works, we can close this and keep it as is.

**Pull request closed without merging**
