### PR TITLE
Feat/use datatorget envs parameter refactoring

### PR DESCRIPTION
**Pull request by karlknowit**
# What was done
Refactor endpoints to use new datatorget ssm parameter. Also refactored booking-api to be able to handle the new format returned from outlook

# How was it done
Solved it fetching the datatorget ssm parameter instead of outlook.
Removed unused search-api service.

# Why was it solved in this way
To make it easier in the future to change our lambdas to use the new datatorget endpoint, we create one single ssm parameter used on all lambdas making requests to datatorget. The lambda itself is then responsible to add the appropriate path to the endpoint.

# How was it tested
Tested by deploying the outlook ssm parameter and changed the lambdas accordingly. Changed the functions to handle the new response type.

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/256)

**Review by sepehrnoor — APPROVED** [review]
No issues here. Ship it!

**Comment by helsingborgsstad** [comment]
Task linked: [CU-1k6vdkv Refaktorera SSM envs i api-repot](https://app.clickup.com/t/1k6vdkv)

**Review by dannil76 — APPROVED** [review]
Looks fine to me

**Comment by karlknowit** [comment]
This one can be closed in favour for:
https://github.com/helsingborg-stad/helsingborg-io-sls-api/pull/258

**Pull request closed without merging**
