### PR TITLE
feat: lambda iam permissions tightened CU-bjtqgf

### PR DESCRIPTION
**Pull request by yo-l1982**
## Feature description
Tighten IAM-permissions and small env var fix for deploys.

## Solution description
Moved config to json file to be readable in serverless.yaml

## What areas is affected by these changes?.
Should not affect anything

## Is there any existing behavior change of other features due to this code change?
No

## Was this feature tested in the following environments?
- [x] Your personal AWS environment.
- [ ] Your local Serverless environment.

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-bjtqgf Gå igenom rättigheterna vi har i Lamdas (enligt HiQ:s granskning)](https://app.clickup.com/t/bjtqgf)

**Review by dannil76 — COMMENTED** [review]
Got this respone when posting to endpoint /auth/token with this payload:
{
    "grant_type": "authorization_code",
    "code": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJzb25hbE51bWJlciI6IjE5NjAwMTE5ODY4NSIsImV4cCI6MTYzMTc1NDA1OCwiaWF0IjoxNjExNzUyODU4fQ.G_P6Ptwi_przVC8NUcLDukBooyrS0RI6NRW66JyQXRg"
}

Response
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "status": "500",
    "code": "500",
    "title": "InternalServerError",
    "detail": "The server encountered an unexpected condition that prevented it from fulfilling the request.",
    "message": "User: arn:aws:sts::020402302769:assumed-role/authorizer-dev-eu-north-1-lambdaRole/authorizer-dev-generateToken is not authorized to perform: secretsmanager:GetSecretValue on resource: dev/token/authorization/code/secret",
    "stack": "InternalServerError: User: arn:aws:sts::020402302769:assumed-role/authorizer-dev-eu-north-1-lambdaRole/authorizer-dev-generateToken is not authorized to perform: secretsmanager:GetSecretValue on resource: dev/token/authorization/code/secret\n    at throwError (/var/task/lambdas/webpack:/Users/dannilsson/Documents/Web/GIT/helsingborg-io-sls-api/node_modules/@helsingborg-stad/npm-api-error-handling/src/index.js:23:1)\n    at validateToken (/var/task/lambdas/webpack:/Users/dannilsson/Documents/Web/GIT/helsingborg-io-sls-api/services/auth/token/lambdas/generateToken.js:118:15)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at Runtime.main [as handler] (/var/task/lambdas/webpack:/Users/dannilsson/Documents/Web/GIT/helsingborg-io-sls-api/services/auth/token/lambdas/generateToken.js:28:51)"
  }
}

**Comment by yo-l1982** [comment]
Yeah the arns was wrong here @dannil76 
I have updated it now.

**Comment by dannil76** [comment]
Trying to deploy service bankid-ms and got this error?
Skärmavbild 2021-04-19 kl  23 09 08

**Comment by yo-l1982** [comment]
@dannil76 Lets see if i managed to fix it this time. Deploys on all services now.

**Review by dannil76 — APPROVED** [review]

**Pull request merged**
