### PR TITLE
fix: upload api crashes when payload is empty

### PR DESCRIPTION
**Pull request by petter-a**
Fixed check for body content to exist and gracefully return errorcode if not

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/306)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-k3bfny Uppladdningslambda crashar när tomt request body skickas in](https://app.clickup.com/t/k3bfny)

**Comment by petter-a** [comment]
> Looks ok. Is it tested?

curl --location --request POST 'https://XXXXX/dev/users/me/attachments' \
--header 'Content-Type: application/json' \
--header 'x-api-key: XXXXX' \
--header 'Authorization: Bearer XXXXXX'

"message": "Body data is missing in request"

**Comment by dannil76** [comment]
@petter-a is this ready to rebase?

**Pull request merged**
