### PR TITLE
Feat/bookables administrators search

### PR DESCRIPTION
**Pull request by karlknowit**
# What was solved
Added new endpoint for fetching administrators belonging to a specific mailbox group

# How was it solved
Solved it by adding a new lambda function which takes an email (or whatever string) as parameter. This parameter is then checked against our saved shared emails in our system. If it doesn't exist then return failure otherwise it makes a request against datatorget for fetching administrators emails. 

# Why was it solved in this way
By adding a check if the email exists in our system, we ca be safe that we only make requests against datatorget with valid email addresses. 

# How was it tested
The service is deployed in my sandbox account. Tried the endpoint in postman with email that existed in our system and without. Checked the result and updated the lambda accordingly.

### CODE REVIEW

**Comment by sebastianthulin** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/259)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-1hdqgr6 Backend för att få fram vilka handläggare som tillhör en specifik funktionsbrevlåda](https://app.clickup.com/t/1hdqgr6)

**Comment by helsingborgsstad** [comment]
Task linked: [CU-1hyy571 Ta fram backend för att söka efter gamla bokningar](https://app.clickup.com/t/1hyy571)

**Review by sepehrnoor — APPROVED** [review]
Shippit!

**Pull request merged**
