### PR TITLE
feat: add decrypt access cu-g31bmk

### PR DESCRIPTION
**Pull request by yo-l1982**
## Feature description
Adds access to KMS CMK for decryption to lambdas that speaks to encrypted tables users and cases and S3 attachments.

## Solution description
Add IAM permission

## What areas is affected by these changes?.
Infrastructure

## Is there any excisting behavior change of other features due to this code change?
No

## Covered unit tests cases / E2E test cases?
no

## Was this feature tested in the following environments?
- [x] Your personal AWS environment.
- [ ] Your local Serverless environment.

### CODE REVIEW

**Comment by helsingborgsstad** [comment]
Task linked: [CU-g31bmk IAM rättigheter till CMK för lamdbor som kommunicerar med krypterade S3 och dynamo](https://app.clickup.com/t/g31bmk)

**Review by dannil76 — APPROVED** [review]

**Comment by Sven65** [comment]
How do I test? I assume I should deploy it to my AWS sandbox, but what happens after that? What result am I expecting?

**Comment by yo-l1982** [comment]
> How do I test? I assume I should deploy it to my AWS sandbox, but what happens after that? What result am I expecting?

Yeah bad PR from me.
This is what is needed to use the non merged PRs
https://github.com/helsingborg-stad/helsingborg-io-sls-resources/pull/50
https://github.com/helsingborg-stad/helsingborg-io-sls-resources/pull/51

**Comment by Sven65** [comment]
Tried to test it, using the instructions from helsingborg-stad/helsingborg-io-sls-resources#50 and helsingborg-stad/helsingborg-io-sls-resources#51, adding the KMS key as instructed, which failed in zsh with aws-vault.

**Review by KenthLjungHBG — APPROVED** [review]
Together with helsingborg-stad/helsingborg-io-sls-resources#50 and helsingborg-stad/helsingborg-io-sls-resources#51 the app now seems to work correctly. App throws no errors and cases are correctly inserted into the encrypted dynamo table.

Deployment required `sls remove` before `sls deploy` for lambdas because of custom resources. Might have to look into this/document this for future (re)deployments. [This link](https://forums.aws.amazon.com/thread.jspa?messageID=713762) seems to be relevant.

**Pull request merged**
